### ISSUE TITLE
Add Node 6.10.0 to match up with latest Amazon Lambda announcement

### ISSUE THREAD

**Issue by rmm5t** [kkarczmarczyk/docker-node-yarn#14]
Related to #9.

https://aws.amazon.com/about-aws/whats-new/2017/03/aws-lambda-supports-node-js-6-10/

**Comment by kkarczmarczyk** [comment]
Yep, but image node:6.10 has yarn build in, so my dockerfile is unnecessary for that version.

**Comment by rmm5t** [comment]
Oh. Awesome. Didn't realize that. Thanks for the tip.
