### ISSUE TITLE
Support for Yarn 0.17

### ISSUE THREAD

**Issue by alansouzati** [kkarczmarczyk/docker-node-yarn#4]
Whenever I try to install this image I get 0.16.1, is there a way to make sure the latest yarn will be installed?

**Comment by kkarczmarczyk** [comment]
> Whenever I try to install this image I get 0.16.1, is there a way to make sure the latest yarn will be installed?

Whenever yarn's contributors release new version I must trigger images to rebuild. You're right, yesterday was 0.16.1, but today it's 0.17.3 - check this out! You must delete kkarczmarczyk/node-yarn containters/images, and download it once again. 

Also, I found solution for automate this process, so future releases of yarn should be up-to-date in my docker images - it's easy to do, but I don't have time today - I must write hook for checking yarn github repo and make POST request to hub.docker.com for trigger my images, so currently I must trigger this action manually.

**Comment by alansouzati** [comment]
cool, thanks for the heads up.
