### ISSUE TITLE
Use the new yarn installer

### ISSUE THREAD

**Issue by orf** [kkarczmarczyk/docker-node-yarn#6]
Here: https://yarnpkg.com/en/docs/install#alternatives-tab

`curl -o- -L https://yarnpkg.com/install.sh | bash`?

**Comment by codemonkey800** [comment]
As a side note, the Yarn page also recommends to NOT install it via npm:

> Note: Installation via npm is generally not recommended. npm is non-determinstic, packages are not signed, and npm does not perform any integrity checks other than a basic SHA1 hash, which is a security risk when installing system-wide apps.
>
> For these reasons, it is highly recommended that you install Yarn through the installation method best suited to your operating system.

https://yarnpkg.com/en/docs/install#alternatives-tab

Since the `node:latest` image is based on debian, you could also use `apt-get`:

```sh
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
```

https://yarnpkg.com/en/docs/install#linux-tab
